config/routes.rb
Rails.application.routes.draw do

  resources :post_attachments do
    resources :names
  end

  get 'carts/show'

  resources :post_attachments
  resources :posts
  get 'users/edit'
  get 'users/index'
  get 'users/show'
  get 'users/new'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  resources :products

  get 'welcome/index'
  get 'home/cart'
  get 'home/Contact_us'
  get 'home/Profiles'
  get 'home/snacks'
  get 'home/About_us'
  get 'home/reserve'
  get 'home/order'
  get 'home/lunch'
  get 'home/breakfst'
  get 'home/real'

  root 'home#real'

end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :post

  has_many :names
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with :name => "admin", :password => "secret", only: [:show, :edit, :update, :destroy]


  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
    respond_to do |format|
      if @post_attachment.update(post_attachment_params)
        format.html { redirect_to @post_attachment.post, notice: 'Post attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_attachment }
      else
        format.html { render :edit }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_attachments_url, notice: 'Post attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :avatar)
    end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/post_attachments/_form.html.erb
<div class="container">
  <%= image_tag @post_attachment.avatar %>
  <%= form_for(@post_attachment) do |f| %>
      <% if @post_attachment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@post_attachment.errors.count, "error") %> prohibited this post_attachment from being saved:</h2>

            <ul>
              <% @post_attachment.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :post_id %><br>
        <%= f.number_field :post_id %>
      </div>
      <div class="field">
        <%= f.label :avatar %><br>
        <%= f.text_field :avatar %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/post_attachments/edit.html.erb
<div class="container">
  <h1>Editing Products</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @post_attachment %> |
  <%= link_to 'Back', post_attachments_path %>

</div>

app/views/post_attachments/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Our Availables Product Now</h1>
<div class="row">
  <table>
    <thead>

    </thead>

    <tbody>
    <% @post_attachments.each do |post_attachment| %>
        <tr>
          <%=link_to (image_tag post_attachment.avatar, :class => "wat" ), post_attachment %>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>


  <br>

</div>

app/views/post_attachments/new.html.erb
<div class="container">
  <h1>New Product</h1>

  <%= render 'form' %>

  <%= link_to 'Back', post_attachments_path %>

</div>

app/views/post_attachments/show.html.erb
<div class="container">
  <div class="ccontainer">
    <p id="notice"><%= notice %></p>
    <%= image_tag @post_attachment.avatar %>


    <td><%= @post_attachment.post_id %></td>
    <td><%= @post_attachment.avatar %></td>
    <td><%= link_to 'Show', @post_attachment %></td>
    <td><%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %></td>
    <td><%= link_to 'Destroy', @post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </div>
</div>