config/routes.rb
Rails.application.routes.draw do

  resources :post_attachments do
    resources :names
  end

  get 'carts/show'

  resources :post_attachments
  resources :posts
  get 'users/edit'
  get 'users/index'
  get 'users/show'
  get 'users/new'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  resources :products

  get 'welcome/index'
  get 'home/cart'
  get 'home/Contact_us'
  get 'home/Profiles'
  get 'home/snacks'
  get 'home/About_us'
  get 'home/reserve'
  get 'home/order'
  get 'home/lunch'
  get 'home/breakfst'
  get 'home/real'

  root 'home#real'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_attachments
  accepts_nested_attributes_for :post_attachments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with :name => "admin", :password => "ElenorArandiaAdmin1234"


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_attachments = @post.post_attachments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post_attachment = @post.post_attachments.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        params[:post_attachments]['avatar'].each do |a|
          @post_attachment = @post.post_attachments.create!(:avatar => a, :post_id => @post.id)
        end
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, post_attachments_attributes: [:id, :post_id, :avatar])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container">
  <%= form_for(@post, :html => { :multipart => true }) do |f| %>
      <% if @post.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
              <% @post.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>

      <%= f.fields_for :post_attachments do |p| %>
          <div class="field">
            <%= p.label :avatar %><br>
            <%= p.file_field :avatar, :multiple => true, name: "post_attachments[avatar][]" %>
          </div>
      <% end %>

      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>

</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Editing Post</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>

</div>

app/views/posts/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Listing Posts</h1>

  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_post_path %>

</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New Post</h1>

  <%= render 'form' %>

  <%= link_to 'Back', posts_path %>

</div>

app/views/posts/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <% @post_attachments.each do |p| %>
      <%= image_tag p.avatar_url %>
      <%= link_to "Edit Attachment", edit_post_attachment_path(p) %>
  <% end %>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>

</div>