config/routes.rb
Rails.application.routes.draw do

  resources :post_attachments do
    resources :names
  end

  get 'carts/show'

  resources :post_attachments
  resources :posts
  get 'users/edit'
  get 'users/index'
  get 'users/show'
  get 'users/new'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resource :cart, only: [:show] do
    put 'add/:product_id', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  resources :products

  get 'welcome/index'
  get 'home/cart'
  get 'home/Contact_us'
  get 'home/Profiles'
  get 'home/snacks'
  get 'home/About_us'
  get 'home/reserve'
  get 'home/order'
  get 'home/lunch'
  get 'home/breakfst'
  get 'home/real'

  root 'home#real'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :menus

  has_many :comments
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/name.rb
class Name < ActiveRecord::Base
  belongs_to :post_attachment
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_attachments
  accepts_nested_attributes_for :post_attachments
end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :post

  has_many :names
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def cart_count
    $redis.scard "cart#{id}"
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def cart_action(current_user_id)
    if $redis.sismember "cart#{current_user_id}", :id
      "Remove from"
    else
      "Add to"
    end
  end
  def show

  end


  def add
    $redis.sadd current_user_cart, params[:product_id]
    render json: current_user.cart_count, status: 200
  end

  def remove
    $redis.srem current_user_cart, params[:product_id]
    render json: current_user.cart_count, status: 200
  end

  private

  def current_user_cart
    "cart#{current_user.id}"
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @menu = Menu.find(params[:menu_id])
    @comment = @menu.comments.create(comment_params)
    redirect_to menus_path(@menu)
  end

  def destroy
    @article = Menu.find(params[:article_id])
    @comment = @menu.comments.find(params[:id])
    @comment.destroy
    redirect_to menus_path(@menu)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index1
    @article = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def destroy
    @article = Article.find (params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  def create
    @post_attachment = PostAttachment.find(params[:post_attachment_id])
    @name = @post_attachment.names.create(name_params)
    redirect_to post_attachments_path(@post_attachment)
  end

  private
  def name_params
    params.require(:name).permit(:commenter, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with :name => "admin", :password => "ElenorArandiaAdmin1234"


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_attachments = @post.post_attachments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post_attachment = @post.post_attachments.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        params[:post_attachments]['avatar'].each do |a|
          @post_attachment = @post.post_attachments.create!(:avatar => a, :post_id => @post.id)
        end
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, post_attachments_attributes: [:id, :post_id, :avatar])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.all
  end

  def create
    @user = User.new(params[user_params])

    if @user.save
      redirect_to @user
    end
  else
    render 'new'
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to  @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
  def user_params
    params.require(:users).permit(:user, :price)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bulaloan</title>
  <link rel="shortcut icon" href="/assets/proposal_logo.png" type="image/x-icon"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="back">
    <div class="container">
      <img src="/assets/proposal_logo.png" alt="logo" class="image"/>
      <h1>Mami Bulalo Papaitan Tapsilogan</h1>
      <h4>"The place to taste best Filipino dishes."</h4>
    </div>
</div>
  <nav class="navbar">
    <div class="container-fluid container">
      <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target="#navbarToggle">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-header">
        </div>
      </div>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <ul class="nav navbar-nav navbar-right navigation" id="trans-nav">

          <li class="nav-color" style="border-top-left-radius: 20px"><%= link_to 'Home', home_real_path  %></i></li>

          <li class="nav-color"><a href="/post_attachments">Menu</a></li>
              <li class="nav-color"><%= link_to 'About Us', home_About_us_path %></li>
              <li class="nav-color"><%= link_to 'Contact Us', home_Contact_us_path %></li>


          <li>
            <%if signed_in?%>

              <li class="nav-color"><%=link_to current_user.email, edit_user_registration_path%></li>
              <li class="nav-color"><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
          <%else%>
              <li class="nav-color"><%=link_to "Register", new_user_registration_path%></li>
              <li class="nav-color"><%=link_to "Login", new_user_session_path%></li>
          <%end%>
          </li>
          <li class="nav-color"  style="border-top-right-radius: 20px"><a href="/posts">Owner</a></li>
        </ul>
      </div>
    </div>
  </nav>

<%= yield %>
<div class="back2">
  <div class="container">
     <center><p class="copy">&copy;Tapsilogan : All Rights Reserved 2015</p></center>
    </div>
</div>
</body>
<script>
    $(function(){
        $(".nav-brand").tooltip();
        $(".popover-trigger").popover({
            trigger:"focus"
        });
        $('.carousel').carousel({
            interval: 20000
        })
    });
</script>
</html>